name:                pointofsale
version:             0.1.0.0
github:              "HelgeStenstrom/pointofsale"
license:             BSD3
author:              "Helge Stenström"
maintainer:          "h.stenstrom@gmail.com"
copyright:           "Helge Stenström 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            HelgeCategoryUnset

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/HelgeStenstrom/pointofsale#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  pointofsale-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pointofsale

tests:
  pointofsale-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pointofsale
